// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuqetyuqfgotnyicdyoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cWV0eXVxZmdvdG55aWNkeW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTI3NjAsImV4cCI6MjA2MTE2ODc2MH0.ZweDPnpIO1h-rtj2V-8qcHciOG12NORlHnj29lfwG08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);